name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Regenerate docs
      run: |
            rm -rf docs
            ./gradlew dokkaHtml
            mv app/build/dokka/html ./docs
    - name: Push docs
      run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "Actions Bot"
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "[Auto] update docs"
          git push -u origin master
